- id: readme-generator-update
  name: README Generator Update
  description: Updates README.md from template configuration
  entry: node src/generator.js
  language: node
  args: [config/readme-config.json, README.md, templates/default.hbs]
  files: '.*'
  require_serial: true
  pass_filenames: false

- id: readme-generator-dry-validate
  name: README Generator Dry Validate
  description: Fails if README.md would change from template/config (does not generate or update)
  entry: node src/generator.js --validate-only
  language: node
  args: [config/readme-config.json, README.md, templates/default.hbs]
  files: '.*'
  require_serial: true
  pass_filenames: false
