name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  actions: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4.2.0
        id: release
        with:
          release-type: node
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json
          token: ${{ secrets.GITHUB_TOKEN }}

      # The logic below will be executed when a release is created
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: 20.x
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci
        if: ${{ steps.release.outputs.release_created }}

      - run: npm test
        if: ${{ steps.release.outputs.release_created }}

      # Optional: Publish to npm registry when a release is created
      # - run: npm publish
      #   if: ${{ steps.release.outputs.release_created }}
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
